[package]
name = "hiquant-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hiquant-core.workspace = true
hiquant-data.workspace = true
hiquant-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
thiserror.workspace = true
tracing.workspace = true
rusqlite.workspace = true
async-trait.workspace = true
